
# Default config

# Set default language
languageCode: "en-gb"

# Site title
title: "Sample Feeds"

# Configure the themes
theme: ["sample-feeds"]

# Enable emoji rendering
enableEmoji: true

# Restrict the output types
outputs:
  home: ["HTML"]
  page: ["HTML"]
  section: ["HTML"]
  taxonomy: ["HTML"]
  term: ["HTML"]

# Disable tags, categories, and RSS
disableKinds: ["taxonomy", "term", "RSS"]

# Publish to the "build" directory
publishDir: "build"
